(()=>{
  const d=document,$=s=>d.querySelector(s),$$=s=>[...d.querySelectorAll(s)];
  const STORE='cfkh.preview.records.v2',AUDIT='cfkh.preview.audit.v2';
  let records=safeLoad(STORE,[]),audit=safeLoad(AUDIT,[]),quick='',lastCustomCount=0;
  const types=['Knowledge Article','Troubleshooting Guide','SOP','Governance Standard','Known Error','Service Request'];
  const systems=['Lightspeed Filter','SmartShield','ChromeOS','Chrome Browser','Admin Console'];
  const statuses=['Draft','In Review','Approved','Needs Review','Archived'];
  function safeLoad(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
  function persist(){localStorage.setItem(STORE,JSON.stringify(records));localStorage.setItem(AUDIT,JSON.stringify(audit))}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function date(){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date())}
  function stamp(){return new Date().toISOString()}
  function prefix(t){return({SOP:'CF-SOP','Troubleshooting Guide':'CF-TG','Knowledge Article':'CF-KB','Governance Standard':'CF-GOV','Known Error':'CF-KE','Service Request':'CF-SR'})[t]||'CF-KB'}
  function nextId(t){return `${prefix(t)}-${String(records.filter(r=>r.type===t).length+100).padStart(3,'0')}`}
  function cls(s){return s==='Approved'?'approved':s==='In Review'?'review':s==='Needs Review'?'needs':'draft'}
  function note(message){let n=$('.studio-toast');if(!n){n=d.createElement('div');n.className='studio-toast';d.body.append(n)}n.textContent=message;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2100)}
  function log(action,r,detail){audit.unshift({time:stamp(),action,articleId:r.id,title:r.title,detail:detail||''});audit=audit.slice(0,30);persist()}
  function matches(r){const q=($('#q')?.value||'').trim().toLowerCase(),t=$('#type')?.value||'',sy=$('#system')?.value||'',st=$('#status')?.value||'',tab=$('.tab.active')?.dataset.tab||'',approved=$('#approved')?.classList.contains('active');if(t&&r.type!==t)return false;if(sy&&r.system!==sy)return false;if(st&&r.status!==st)return false;if(tab&&r.type!==tab)return false;if(approved&&r.status!=='Approved')return false;if(quick==='review'&&!['In Review','Needs Review'].includes(r.status))return false;if(quick==='drafts'&&r.status!=='Draft')return false;if(quick==='favorites'&&!r.favorite)return false;if(q&&!([r.id,r.type,r.title,r.system,r.status,r.audience,r.owner,r.summary,...r.tags].join(' ').toLowerCase().includes(q)))return false;return r.status!=='Archived'}
  function sorted(list){const mode=$('#sort')?.value||'recent';return list.slice().sort((a,b)=>{if(mode==='title')return a.title.localeCompare(b.title);if(mode==='status'){const o={Approved:1,'In Review':2,'Needs Review':3,Draft:4,Archived:5};return o[a.status]-o[b.status]}return String(b.updatedAt).localeCompare(String(a.updatedAt))})}
  function renderCards(){const g=$('#cards');if(!g)return;g.querySelectorAll('.studio-card').forEach(x=>x.remove());const visible=sorted(records.filter(matches));visible.forEach(r=>g.insertAdjacentHTML('beforeend',card(r)));bindCardActions();updateCounts(visible.length)}
  function card(r){return `<article class="card studio-card"><div class="top"><span class="badge type">${esc(r.type)}</span><div style="display:flex;gap:6px"><span class="badge ${cls(r.status)}">${esc(r.status)}</span><button class="favorite ${r.favorite?'on':''}" data-favorite="${esc(r.id)}">${r.favorite?'★':'☆'}</button></div></div><h3>${esc(r.title)}</h3><div class="id">${esc(r.id)} · ${esc(r.owner)}</div><p>${esc(r.summary)}</p><div class="meta"><div><b>System</b><span>${esc(r.system)}</span></div><div><b>Audience</b><span>${esc(r.audience)}</span></div></div><div class="tags">${r.tags.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="studio-card-actions"><button data-process="${esc(r.id)}">Process</button><button data-transition="${esc(r.id)}|In Review">Review</button><button data-transition="${esc(r.id)}|Approved">Publish</button></div><div class="foot"><span>Updated ${esc(r.updated)}</span><button data-audit="${esc(r.id)}">Audit</button></div></article>`}
  function bindCardActions(){$$('[data-process]').forEach(b=>b.onclick=()=>process(b.dataset.process));$$('[data-transition]').forEach(b=>b.onclick=()=>transition(...b.dataset.transition.split('|')));$$('[data-favorite]').forEach(b=>b.onclick=()=>{const r=find(b.dataset.favorite);r.favorite=!r.favorite;persist();renderCards();note(r.favorite?'Saved to My Favorites':'Removed from My Favorites')});$$('[data-audit]').forEach(b=>b.onclick=()=>showAudit(b.dataset.audit))}
  function updateCounts(customVisible){const customReview=records.filter(r=>['In Review','Needs Review'].includes(r.status)).length;['#studioReviewCount','#reviewCount'].forEach(s=>{const e=$(s);if(e)e.textContent=s==='#reviewCount'?2+customReview:customReview});const h=$('.health p');if(h)h.textContent=`Preview catalog includes ${records.length} created records; ${customReview} are in lifecycle review. Shared Apps Script service follows this same workflow.`;lastCustomCount=customVisible}
  function modal(){let m=$('#studioModal');if(m)return m;m=d.createElement('aside');m.id='studioModal';m.className='studio-modal';m.innerHTML='<button class="studio-close" id="studioClose">×</button><h2 id="studioTitle"></h2><p id="studioSubtitle"></p><div id="studioBody"></div>';d.body.append(m);$('#studioClose').onclick=close;return m}
  function open(title,subtitle,body){modal();$('#studioTitle').textContent=title;$('#studioSubtitle').textContent=subtitle;$('#studioBody').innerHTML=body;$('#studioModal').classList.add('open')}
  function close(){$('#studioModal')?.classList.remove('open')}
  function createForm(type='Knowledge Article'){open(`Create ${type}`,'Capture operational purpose, evidence context, processing notes, and a lifecycle decision.',`<form id="createForm"><div class="studio-form"><div class="studio-field"><label>Content Type</label><select id="cType">${types.map(x=>`<option ${x===type?'selected':''}>${x}</option>`).join('')}</select></div><div class="studio-field"><label>System / Solution</label><select id="cSystem">${systems.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="studio-field full"><label>Title</label><input id="cTitle" required placeholder="Clear, task-oriented article title"></div><div class="studio-field"><label>Audience</label><input id="cAudience" value="Help Desk · School Tech"></div><div class="studio-field"><label>Owner</label><input id="cOwner" value="Content Filtering"></div><div class="studio-field full"><label>Purpose / Summary</label><textarea id="cSummary" required placeholder="Describe the support need, operational outcome, or problem this content resolves."></textarea></div><div class="studio-field"><label>Tags</label><input id="cTags" placeholder="policy, troubleshooting, logs"></div><div class="studio-field"><label>Evidence / Source Reference</label><input id="cSource" placeholder="Ticket, SOP, vendor case, or document"></div><div class="studio-field full"><label>Procedure / Processing Notes</label><textarea id="cNotes" placeholder="Add steps, validation checks, escalation points, or review notes."></textarea></div></div><div class="studio-footer"><button type="button" id="draftCreate">Save Draft</button><button type="button" class="review" id="reviewCreate">Submit for Review</button><button type="submit" class="publish">Approve & Publish</button></div></form>`);$('#createForm').onsubmit=e=>{e.preventDefault();create('Approved')};$('#draftCreate').onclick=()=>create('Draft');$('#reviewCreate').onclick=()=>create('In Review')}
  function create(status){const form=$('#createForm');if(!form.reportValidity())return;const t=$('#cType').value,r={id:nextId(t),type:t,status,title:$('#cTitle').value.trim(),system:$('#cSystem').value,audience:$('#cAudience').value.trim()||'Help Desk · School Tech',owner:$('#cOwner').value.trim()||'Content Filtering',summary:$('#cSummary').value.trim(),tags:$('#cTags').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,8),source:$('#cSource').value.trim(),notes:$('#cNotes').value.trim(),createdAt:stamp(),updatedAt:stamp(),updated:date(),revision:1,favorite:false};if(!r.tags.length)r.tags=['new content'];records.unshift(r);log('CREATE',r,`Created as ${status}`);persist();close();renderCards();note(`${r.id} created as ${status}`);process(r.id)}
  function process(id){const r=find(id);if(!r)return;open(`Process ${r.id}`,`${r.type} · revision ${r.revision} · updated ${r.updated}`,`<div class="studio-form"><div class="studio-field full"><label>Title</label><input value="${esc(r.title)}" disabled></div><div class="studio-field"><label>Lifecycle Status</label><select id="pStatus">${statuses.map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="studio-field"><label>Owner</label><input id="pOwner" value="${esc(r.owner)}"></div><div class="studio-field full"><label>Processing Notes</label><textarea id="pNotes">${esc(r.notes)}</textarea></div><div class="studio-field full"><label>Evidence / Source Reference</label><input id="pSource" value="${esc(r.source)}"></div></div><div class="studio-footer"><button id="saveProcess">Save Changes</button><button class="review" id="returnDraft">Return to Draft</button><button class="publish" id="approvePublish">Approve & Publish</button></div>`);$('#saveProcess').onclick=()=>updateProcess(r.id,$('#pStatus').value);$('#returnDraft').onclick=()=>updateProcess(r.id,'Draft');$('#approvePublish').onclick=()=>updateProcess(r.id,'Approved')}
  function updateProcess(id,next){const r=find(id);r.status=next;r.owner=$('#pOwner').value.trim()||r.owner;r.notes=$('#pNotes').value.trim();r.source=$('#pSource').value.trim();r.updatedAt=stamp();r.updated=date();r.revision+=1;log('PROCESS',r,`Moved to ${next}`);persist();close();renderCards();note(`${r.id} updated`)}
  function transition(id,next){const r=find(id);r.status=next;r.updatedAt=stamp();r.updated=date();r.revision+=1;log('TRANSITION',r,`Moved to ${next}`);persist();renderCards();note(`${r.id} moved to ${next}`)}
  function find(id){return records.find(r=>r.id===id)}
  function reviewQueue(){const q=records.filter(r=>['In Review','Needs Review'].includes(r.status));open('Process Review Queue','Records awaiting approval, ownership confirmation, or a governance decision.',q.length?`<div class="studio-actions">${q.map(r=>`<button class="studio-create" data-queue="${esc(r.id)}"><span class="studio-icon">✓</span><span><b>${esc(r.title)}</b><small>${esc(r.id)} · ${esc(r.status)} · ${esc(r.owner)}</small></span><i>›</i></button>`).join('')}</div>`:'<div class="studio-section" style="padding:12px">No created records are waiting for review.</div>');$$('[data-queue]').forEach(b=>b.onclick=()=>process(b.dataset.queue))}
  function drafts(){const list=records.filter(r=>r.status==='Draft');open('Draft Workspace','Draft articles are retained here until submitted for review or approved.',list.length?`<div class="studio-actions">${list.map(r=>`<button class="studio-create" data-draft="${esc(r.id)}"><span class="studio-icon">✎</span><span><b>${esc(r.title)}</b><small>${esc(r.id)} · updated ${esc(r.updated)}</small></span><i>›</i></button>`).join('')}</div>`:'<div class="studio-section" style="padding:12px">No draft records are currently available.</div>');$$('[data-draft]').forEach(b=>b.onclick=()=>process(b.dataset.draft))}
  function showAudit(id){const list=audit.filter(a=>!id||a.articleId===id);open(id?'Audit Trail · '+id:'Preview Audit Activity','Every preview content action is retained locally so you can inspect the workflow before the shared Apps Script service is connected.',list.length?`<div class="studio-section" style="margin-top:14px">${list.map(a=>`<div class="studio-audit"><b>${esc(a.action)}</b> · ${esc(a.articleId)}<br>${esc(new Date(a.time).toLocaleString())}<br>${esc(a.detail)}</div>`).join('')}</div>`:'<div class="studio-section" style="padding:12px">No preview activity has been recorded yet.</div>')}
  function settings(){open('Preview Lifecycle Settings','This preview mirrors the production lifecycle and access model. The Apps Script deployment will persist these controls in the shared configuration sheet.',`<div class="studio-section" style="margin-top:14px"><header>Workflow <span>PREVIEW</span></header><div class="studio-audit"><b>Lifecycle</b><br>Draft → In Review → Approved → Needs Review → Archived</div><div class="studio-audit"><b>Content types</b><br>${types.join(' · ')}</div><div class="studio-audit"><b>Role model</b><br>Viewer, Editor, Administrator. The production build enforces these server-side.</div></div><div class="studio-footer"><button class="publish" id="viewAudit">View Preview Audit</button></div>`);$('#viewAudit').onclick=()=>showAudit()}
  function panel(){const right=$('.right');if(!right)return;right.innerHTML=`<div class="head"><h2>Content Studio</h2><span class="micro">Create</span></div><section class="studio-section"><header>New Controlled Content <span>INTAKE</span></header><div class="studio-actions"><button class="studio-create" data-new="Knowledge Article"><span class="studio-icon">✎</span><span><b>Knowledge Article</b><small>Guidance, FAQ, operational context</small></span><i>›</i></button><button class="studio-create" data-new="Troubleshooting Guide"><span class="studio-icon">⌁</span><span><b>Troubleshooting Guide</b><small>Symptoms, checks, resolution</small></span><i>›</i></button><button class="studio-create" data-new="SOP"><span class="studio-icon">▤</span><span><b>Standard Operating Procedure</b><small>Controlled task process</small></span><i>›</i></button></div></section><section class="studio-section"><header>Process Content <span>WORKFLOW</span></header><button class="studio-row" id="previewReview">Review Queue <span class="studio-badge" id="studioReviewCount">0</span></button><button class="studio-row" id="previewDrafts">Draft Workspace <span>›</span></button><button class="studio-row" id="previewAudit">Audit Activity <span>›</span></button></section><section class="studio-section"><header>Lifecycle Control <span>GOVERNANCE</span></header><div style="padding:9px;color:#50677f;font-size:10px;line-height:1.45">Draft → In Review → Approved → Needs Review → Archived. Preview actions are persisted locally; the Apps Script service uses the same workflow against the shared catalog.</div></section><button class="studio-cta" id="previewBuilder">Open Article Builder</button>`;$$('[data-new]').forEach(b=>b.onclick=()=>createForm(b.dataset.new));$('#previewBuilder').onclick=()=>createForm();$('#previewReview').onclick=reviewQueue;$('#previewDrafts').onclick=drafts;$('#previewAudit').onclick=()=>showAudit();updateCounts(0)}
  function wire(){const baseRender=window.render; if(typeof baseRender==='function'){window.render=function(){baseRender();setTimeout(renderCards,0)}}const sync=()=>setTimeout(renderCards,0);['#q','#type','#system','#status','#sort','#approved','#grid','#list','#reviewBtn','#reset'].forEach(s=>$(s)?.addEventListener('input',sync));['#approved','#grid','#list','#reviewBtn','#reset'].forEach(s=>$(s)?.addEventListener('click',sync));$$('[data-quick]').forEach(b=>b.addEventListener('click',()=>{quick=b.dataset.quick==='fav'?'favorites':b.dataset.quick;sync()}));$$('.tab').forEach(b=>b.addEventListener('click',()=>{quick='';sync()}));$$('.nav').forEach(b=>b.addEventListener('click',()=>{quick=b.dataset.nav==='review'?'review':'';sync()}));$('#adminBtn')?.addEventListener('click',settings)}
  function init(){panel();const bar=$('.commandbar');if(bar&&!$('#previewCreate')){const button=d.createElement('button');button.className='btn admin';button.id='previewCreate';button.textContent='+ Create';button.onclick=()=>createForm();bar.insertBefore(button,$('#adminBtn')||null)}wire();renderCards();const target=$('#cards');if(target)new MutationObserver(()=>setTimeout(renderCards,0)).observe(target,{childList:true})}
  setTimeout(init,200);
})();